### ISSUE TITLE
Override Default Logging Location (Linux)

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/splunkforwarder-formula#14]
### Problem Description:

Current installation uses the Splunk forwarder-agent's default location &mdash; `/opt/splunkforwarder/var/log/splunk`. When `/opt` is a subdirectory of the `/` filesystem, this results in the Splunk agent's activities logging to the `/` filesystem rather than the more-appropriate `/var/log` filesystem. When the `/` filesystem is small (as in [spel](/plus3it/spel.git)) and other similarly poorly-configured applications are writing data into a root-mounted `/opt`, this can contribute to premature space-exhaustion of the `/` filesystem.

### Expected Behavior:

Splunk should log into the `/var/log` filesystem

### Actual Behavior:

Splunk logs to `/opt/splunkforwarder/var/log/splunk`

### Steps to reproduce:

1. Install Splunk forwarder agent with default installation option. 
1. Start Splunk forwarder agent.
1. Examine contents of `/opt/splunkforwarder/var/log/splunk`
1. Check real location of `/opt/splunkforwarder/var/log/splunk` (will be located in `/opt` under `/`)

### Fix recommendation:

It _may_ be possible to create a `/opt/splunkforwarder/etc/log-local.cfg` and individually override each log file destination specified in the `/opt/splunkforwarder/etc/log.cfg`. However, there are a _number_ of values to override and some Splunk agent logging activities use hard-coded destinations. Probably easier and less error-prone to do something like:

````
service splunk stop && \
mv /opt/splunkforwarder/var/log/splunk /var/log/splunk && \
ln -s /var/log/splunk /opt/splunkforwarder/var/log/splunk && \
service splunk start
````

**Comment by lorengordon** [comment]
Closed by #15
